CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "EmployeeSalary" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer NOT NULL,
    salary_component_id integer NOT NULL,
    amount double precision NOT NULL,
    created_at timestamptz NOT NULL,
    created_by integer NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT "PK_EmployeeSalary" PRIMARY KEY (id)
);

CREATE TABLE "User" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "userName" text NOT NULL,
    password text NOT NULL,
    user_type integer NOT NULL,
    created_at timestamptz NOT NULL,
    created_by integer NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY (id)
);

CREATE TABLE "Employee" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "firstName" text NULL,
    "lastName" text NULL,
    address text NULL,
    aadhar_number text NULL,
    aadhar_document text NULL,
    verification boolean NOT NULL,
    designation text NULL,
    "employeeSalaryId" integer NOT NULL,
    created_at timestamptz NOT NULL,
    created_by integer NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT "PK_Employee" PRIMARY KEY (id),
    CONSTRAINT "FK_Employee_EmployeeSalary_employeeSalaryId" FOREIGN KEY ("employeeSalaryId") REFERENCES "EmployeeSalary" (id) ON DELETE CASCADE
);

CREATE TABLE "SalaryComponents" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    component_name text NOT NULL,
    component_type text NOT NULL,
    description text NOT NULL,
    "employeeSalaryId" integer NOT NULL,
    created_at timestamptz NOT NULL,
    created_by integer NOT NULL,
    updated_at timestamptz NOT NULL,
    updated_by integer NOT NULL,
    CONSTRAINT "PK_SalaryComponents" PRIMARY KEY (id),
    CONSTRAINT "FK_SalaryComponents_EmployeeSalary_employeeSalaryId" FOREIGN KEY ("employeeSalaryId") REFERENCES "EmployeeSalary" (id) ON DELETE CASCADE
);

CREATE INDEX "IX_Employee_employeeSalaryId" ON "Employee" ("employeeSalaryId");

CREATE INDEX "IX_SalaryComponents_employeeSalaryId" ON "SalaryComponents" ("employeeSalaryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221114053018_myMigration01', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "User" RENAME COLUMN "userName" TO user_name;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221114064314_SecongMigration', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Employee" DROP CONSTRAINT "FK_Employee_EmployeeSalary_employeeSalaryId";

ALTER TABLE "SalaryComponents" DROP CONSTRAINT "FK_SalaryComponents_EmployeeSalary_employeeSalaryId";

ALTER TABLE "User" ALTER COLUMN user_name DROP NOT NULL;

ALTER TABLE "User" ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE "User" ALTER COLUMN password DROP NOT NULL;

ALTER TABLE "User" ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN "employeeSalaryId" DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN description DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN component_type DROP NOT NULL;

ALTER TABLE "SalaryComponents" ALTER COLUMN component_name DROP NOT NULL;

ALTER TABLE "EmployeeSalary" ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE "EmployeeSalary" ALTER COLUMN salary_component_id DROP NOT NULL;

ALTER TABLE "EmployeeSalary" ALTER COLUMN employee_id DROP NOT NULL;

ALTER TABLE "EmployeeSalary" ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE "EmployeeSalary" ALTER COLUMN amount DROP NOT NULL;

ALTER TABLE "Employee" ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE "Employee" ALTER COLUMN "employeeSalaryId" DROP NOT NULL;

ALTER TABLE "Employee" ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE "Employee" ADD CONSTRAINT "FK_Employee_EmployeeSalary_employeeSalaryId" FOREIGN KEY ("employeeSalaryId") REFERENCES "EmployeeSalary" (id);

ALTER TABLE "SalaryComponents" ADD CONSTRAINT "FK_SalaryComponents_EmployeeSalary_employeeSalaryId" FOREIGN KEY ("employeeSalaryId") REFERENCES "EmployeeSalary" (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221128115158_myMigration02', '7.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221129050824_SerilogToPostG', '7.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221130045358_LogTest', '7.0.0');

COMMIT;

START TRANSACTION;

UPDATE "Employee" SET "lastName" = '' WHERE "lastName" IS NULL;
ALTER TABLE "Employee" ALTER COLUMN "lastName" SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN "lastName" SET DEFAULT '';

UPDATE "Employee" SET "firstName" = '' WHERE "firstName" IS NULL;
ALTER TABLE "Employee" ALTER COLUMN "firstName" SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN "firstName" SET DEFAULT '';

UPDATE "Employee" SET designation = '' WHERE designation IS NULL;
ALTER TABLE "Employee" ALTER COLUMN designation SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN designation SET DEFAULT '';

UPDATE "Employee" SET address = '' WHERE address IS NULL;
ALTER TABLE "Employee" ALTER COLUMN address SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN address SET DEFAULT '';

UPDATE "Employee" SET aadhar_number = '' WHERE aadhar_number IS NULL;
ALTER TABLE "Employee" ALTER COLUMN aadhar_number SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN aadhar_number SET DEFAULT '';

UPDATE "Employee" SET aadhar_document = '' WHERE aadhar_document IS NULL;
ALTER TABLE "Employee" ALTER COLUMN aadhar_document SET NOT NULL;
ALTER TABLE "Employee" ALTER COLUMN aadhar_document SET DEFAULT '';

ALTER TABLE "Employee" ADD department text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD email text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD phone_number text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221201082721_newDetails', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "User" ALTER COLUMN user_type TYPE text;

UPDATE "User" SET user_name = '' WHERE user_name IS NULL;
ALTER TABLE "User" ALTER COLUMN user_name SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN user_name SET DEFAULT '';

UPDATE "User" SET password = '' WHERE password IS NULL;
ALTER TABLE "User" ALTER COLUMN password SET NOT NULL;
ALTER TABLE "User" ALTER COLUMN password SET DEFAULT '';

UPDATE "SalaryComponents" SET description = '' WHERE description IS NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN description SET NOT NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN description SET DEFAULT '';

UPDATE "SalaryComponents" SET component_type = '' WHERE component_type IS NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN component_type SET NOT NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN component_type SET DEFAULT '';

UPDATE "SalaryComponents" SET component_name = '' WHERE component_name IS NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN component_name SET NOT NULL;
ALTER TABLE "SalaryComponents" ALTER COLUMN component_name SET DEFAULT '';

UPDATE "EmployeeSalary" SET salary_component_id = 0 WHERE salary_component_id IS NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN salary_component_id SET NOT NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN salary_component_id SET DEFAULT 0;

UPDATE "EmployeeSalary" SET employee_id = 0 WHERE employee_id IS NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN employee_id SET NOT NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN employee_id SET DEFAULT 0;

UPDATE "EmployeeSalary" SET amount = 0.0 WHERE amount IS NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN amount SET NOT NULL;
ALTER TABLE "EmployeeSalary" ALTER COLUMN amount SET DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221208103747_DecMigration', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Employee" ADD profile_picture text NOT NULL DEFAULT '';

ALTER TABLE "Employee" ADD user_type text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221213110052_addColoums', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "User" DROP CONSTRAINT "FK_User_Employee_employee_id";

DROP INDEX "IX_User_employee_id";

ALTER TABLE "Employee" ALTER COLUMN id DROP IDENTITY;

ALTER TABLE "Employee" ADD CONSTRAINT "FK_Employee_User_id" FOREIGN KEY (id) REFERENCES "User" (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221214092159_useremployee', '7.0.0');

COMMIT;

